name: "â˜ï¸ CD â€” Deploy Docs"

on:
  push:
    branches:
      - main
    paths:
      - "apps/docs/**"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Docs
    steps:
      - name: â• Actions - Checkout
        uses: actions/checkout@v6

      - name: â• Actions - Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: ğŸ“¦ Installing Dependencies
        run: bun ci

      - name: ğŸ“ Format
        run: bun format

      - name: ğŸ” Lint
        run: bun lint

      - name: ğŸš€ Building Documentation
        run: bun run --filter docs build

      - name: ğŸ”§ Setup Pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: next

      - name: ğŸ“¥ Deploying to Github Pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: apps/docs/out

      - uses: actions/deploy-pages@v4
